server:
  port: 8502

spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: admin
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

